## Dependencies

In [1]:
from graph import Graph

In [2]:
g = Graph()

WE OUTCHEA
Adjacency MAtrix 1 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
Adjacency MAtrix 2 [[1 0 1 0 0 1 1 0 0 0 0 0 1 0 1 1]
 [0 1 1 1 0 1 1 0 1 0 0 1 0 0 0 1]
 [1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 0 1 1 0 0 0 0 1 1 0 1 1]
 [1 1 1 0 0 1 1 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 1

In [3]:
g.adj

array([[1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1]], dtype=uint8)

In [4]:
from util import config, file_dir
import numpy as np

In [3]:
knowair_fp = file_dir['knowair_fp']

In [5]:
knowair = np.load(knowair_fp)

In [6]:
feature = knowair[:,:,:-1]

In [16]:
feature[0][11]

array([ 2.79250000e+02,  2.78550000e+02,  2.78950000e+02,  9.47100000e+02,
        2.00000000e-01,  2.00000000e-01,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+02,  0.00000000e+00,  3.50000000e+00,  2.14000000e+01,
        3.00000000e-01,  3.30000000e-01,  1.67000000e+01,  1.00000000e+00,
                   nan,             nan,  2.26000000e+01, -5.00000000e-01,
        6.12323400e-17, -6.94244558e-01,  1.99071424e-01])

In [8]:
metero_var = config['data']['metero_var']
metero_use = config['experiments']['metero_use']
metero_idx = [metero_var.index(var) for var in metero_use]
metero_idx

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [5]:
g.edge_num

73

In [7]:
xtract = 5646

In [9]:
print()