In [95]:
from graph import Graph

In [96]:
g = Graph()

In [97]:
g.edge_attr

tensor([[  0.0000, 270.0000],
        [ 66.4832, 260.6158],
        [ 59.3939, 319.0783],
        [ 71.6785, 229.4607],
        [190.2286, 335.7364],
        [ 79.1589, 349.1931],
        [ 31.1417, 305.1703],
        [114.6005, 285.6000],
        [134.0850, 237.3152],
        [199.8333, 302.1734],
        [184.8506, 304.3607],
        [ 94.3162, 238.8742],
        [ 84.8669, 321.9708],
        [147.9968, 262.7746],
        [ 99.7729, 356.5699],
        [ 73.6927, 346.0692],
        [ 66.4832,  80.7204],
        [  0.0000, 270.0000],
        [ 61.7800,  25.6976],
        [ 37.4377, 162.8257],
        [184.6905, 356.1939],
        [102.1008,  29.9086],
        [ 49.3877,  54.4637],
        [ 61.1644, 313.0310],
        [ 77.6143, 217.6167],
        [156.4283, 318.6490],
        [144.3355, 323.0324],
        [ 40.8258, 201.8801],
        [ 78.8204,   9.8243],
        [ 81.5992, 264.6376],
        [125.5007,  28.4668],
        [ 95.2559,  30.2582],
        [ 59.3939, 138.6426],
        [ 

In [6]:
g.edge_attr

AttributeError: 'Graph' object has no attribute 'edge_attr'

In [1]:
import numpy as np

In [2]:
thing = [[1],[2]]

In [4]:
this = np.array(thing)

In [6]:
this[:,1]

IndexError: index 1 is out of bounds for axis 1 with size 1

In [ ]:
metero_var = config['data']['metero_var']
metero_use = config['experiments']['metero_use']
metero_idx = [metero_var.index(var) for var in metero_use]

In [11]:
lis1 = ['a','b','c','d','e','f',]
lis2 = ['b','d','f']

lis_idx = [lis1.index(x) for x in lis2]

In [12]:
lis_idx

[1, 3, 5]

In [8]:
from util import config, file_dir
metero_var = config['data']['metero_var']
metero_use = config['experiments']['metero_use']
metero_idx = [metero_var.index(var) for var in metero_use]
metero_idx

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22]

In [2]:
import numpy as np
x = np.NaN

In [3]:
y = 1000

In [4]:
y > x

False

In [5]:
x*y

nan

In [14]:
from model.PM25_GNN import GraphGNN
from model.PM25_GNN import PM25_GNN
import torch
from graph import Graph
from dataset import HazeData
graph = Graph()

In [15]:
use_cuda = torch.cuda.is_available()
device = torch.device('cuda' if use_cuda else 'cpu')

city_num = graph.node_num

In [16]:
batch_size = config['train']['batch_size']
epochs = config['train']['epochs']
hist_len = config['train']['hist_len']
pred_len = config['train']['pred_len']
weight_decay = config['train']['weight_decay']
early_stop = config['train']['early_stop']
lr = config['train']['lr']
results_dir = file_dir['results_dir']
dataset_num = config['experiments']['dataset_num']
exp_model = config['experiments']['model']
exp_repeat = config['train']['exp_repeat']

In [22]:
train_data = HazeData(graph, hist_len, pred_len, dataset_num, flag='Train')
val_data = HazeData(graph, hist_len, pred_len, dataset_num, flag='Val')
test_data = HazeData(graph, hist_len, pred_len, dataset_num, flag='Test')
in_dim = train_data.feature.shape[-1] + train_data.pm25.shape[-1]
wind_mean, wind_std = train_data.wind_mean, train_data.wind_std
pm25_mean, pm25_std = test_data.pm25_mean, test_data.pm25_std
gnn_out = 13

meteo_idx:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
meteo_idx:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
meteo_idx:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]


In [23]:
g = GraphGNN(device, graph.edge_index, graph.edge_attr, in_dim, gnn_out, wind_mean, wind_std)
h = PM25_GNN(hist_len, pred_len, in_dim, city_num, batch_size, device, graph.edge_index, graph.edge_attr, wind_mean, wind_std)

In [50]:
edge_src, edge_target = graph.edge_index
edge_attr = graph.edge_attr


In [25]:
edge_attr_ = graph.edge_attr[None, :, :].repeat(node_src.size(0), 1, 1)

IndexError: too many indices for tensor of dimension 2

In [39]:
model = h
model = model.to(device)

In [27]:
train_data

In [28]:
train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size, shuffle=True, drop_last=True)

In [29]:
from tqdm import tqdm


In [31]:
data = tqdm(enumerate(train_loader))

0it [00:00, ?it/s]


TypeError: 'tqdm' object is not subscriptable

In [42]:
for batch_idx, data in tqdm(enumerate(train_loader)):
    pm25, feature, time_arr = data
    #print(pm25)
    pm25 = pm25.to(device)
    #print('feature:', feature)
    feature = feature.to(device)
    pm25_hist = pm25[:, :hist_len]
    #pm25_pred = model(pm25_hist, feature)
    xn = pm25_hist[:,-1]


113it [00:00, 591.28it/s]


In [44]:
x = torch.cat((xn,feature[:,hist_len]),dim=-1)

In [46]:
x = x.contiguous()

In [48]:
node_src = x[:,edge_src]

In [51]:
edge_attr = edge_attr.to(device)

In [52]:
src_wind = node_src[:,:,-2:] * wind_std[None,None,:] + wind_mean[None,None,:]

In [54]:
edge_attr_ = edge_attr[None, :, :].repeat(node_src.size(0), 1, 1)

In [55]:
city_direc = edge_attr_[:,:,1]

In [78]:
city_direc

tensor([[270.0000, 260.6158, 319.0783,  ..., 234.3794,  22.0540, 270.0000],
        [270.0000, 260.6158, 319.0783,  ..., 234.3794,  22.0540, 270.0000],
        [270.0000, 260.6158, 319.0783,  ..., 234.3794,  22.0540, 270.0000],
        ...,
        [270.0000, 260.6158, 319.0783,  ..., 234.3794,  22.0540, 270.0000],
        [270.0000, 260.6158, 319.0783,  ..., 234.3794,  22.0540, 270.0000],
        [270.0000, 260.6158, 319.0783,  ..., 234.3794,  22.0540, 270.0000]],
       dtype=torch.float64)

In [62]:
src_wind_direc = src_wind[:,:,1]

In [64]:
src_wind_direc.shape

torch.Size([32, 73])

In [69]:
city_direc[31]

tensor([270.0000, 260.6158, 319.0783, 229.4607, 335.7364, 349.1931, 305.1703,
        285.6000, 237.3152, 302.1734, 304.3607, 238.8742, 321.9708, 262.7746,
        356.5699, 346.0692,  80.7204, 270.0000,  25.6976, 162.8257, 356.1939,
         29.9086,  54.4637, 313.0310, 217.6167, 318.6490, 323.0324, 201.8801,
          9.8243, 264.6376,  28.4668,  30.2582, 138.6426, 205.1598, 270.0000,
        189.2254, 342.5762,  35.7634, 153.0370, 258.4377, 211.7991, 294.8534,
        297.1723, 203.6409, 328.2257, 239.0977,  30.6075,  38.0201,  49.9112,
        343.1699,  10.1086, 270.0000, 354.2971,  18.1268,  24.6624, 324.6094,
        246.5918, 323.5919, 327.4144, 265.7375,   1.5540, 287.3002,  18.8042,
         17.7236, 154.0694, 174.4309, 161.3471, 172.1887, 270.0000, 144.8298,
        159.6052, 191.0633, 186.3711, 231.9639, 225.4650, 178.9998, 164.6799,
        198.0123, 133.9714, 147.6633, 168.4339, 209.0485, 215.4415, 196.9205,
        325.7402, 270.0000, 189.3033, 243.0796, 212.3771, 279.76

In [82]:
src_wind_direc[0]

tensor([254., 254., 254., 254., 254., 254., 235., 235., 235., 235., 235., 235.,
        235., 231., 231., 231., 231., 231., 231., 231., 231., 211., 211., 211.,
        211., 211., 211., 211., 211., 211., 234., 234., 234., 234., 234., 234.,
        234., 265., 265., 265., 283., 284., 251., 251., 251., 251., 251., 251.,
        251., 251., 240., 240., 240., 240., 240., 214., 214., 214., 214., 214.,
        214., 214., 214., 214., 211., 211., 211., 211., 211., 211., 211., 211.,
        211.])

In [85]:
city_direc[0]

tensor([270.0000, 260.6158, 319.0783, 229.4607, 335.7364, 349.1931, 305.1703,
        285.6000, 237.3152, 302.1734, 304.3607, 238.8742, 321.9708, 262.7746,
        356.5699, 346.0692,  80.7204, 270.0000,  25.6976, 162.8257, 356.1939,
         29.9086,  54.4637, 313.0310, 217.6167, 318.6490, 323.0324, 201.8801,
          9.8243, 264.6376,  28.4668,  30.2582, 138.6426, 205.1598, 270.0000,
        189.2254, 342.5762,  35.7634, 153.0370, 258.4377, 211.7991, 294.8534,
        297.1723, 203.6409, 328.2257, 239.0977,  30.6075,  38.0201,  49.9112,
        343.1699,  10.1086, 270.0000, 354.2971,  18.1268,  24.6624, 324.6094,
        246.5918, 323.5919, 327.4144, 265.7375,   1.5540, 287.3002,  18.8042,
         17.7236, 154.0694, 174.4309, 161.3471, 172.1887, 270.0000, 144.8298,
        159.6052, 191.0633, 186.3711, 231.9639, 225.4650, 178.9998, 164.6799,
        198.0123, 133.9714, 147.6633, 168.4339, 209.0485, 215.4415, 196.9205,
        325.7402, 270.0000, 189.3033, 243.0796, 212.3771, 279.76

In [88]:
edge_attr

tensor([  0., 270.], dtype=torch.float64)

In [92]:
from graph import Graph
graph = Graph()


In [94]:
graph.edge_attr.shape

torch.Size([256, 2])